### PR TITLE
Vue 3

### PR DESCRIPTION
**Pull request by raimund-schluessler**

### CODE REVIEW

**Comment by susnux** [comment]
We now have vue3 support using `@nextcloud/eslint-config/vue3`.

We should in the next major either drop vue2 or make vue3 the default and rename vue2.

**Comment by susnux** [comment]
> Did you have new about this subject?

No, there is Vue3 support in latest released version. Other libraries are also available with vue3 support.

**Comment by StCyr** [comment]
> > Did you have new about this subject?
> 
> No, there is Vue3 support in latest released version. Other libraries are also available with vue3 support.

What do you mean? Does this package support vue3 eventually?

According to https://github.com/nextcloud-libraries/webpack-vue-config/pull/331, webpack-vue-config is waiting for this PR in order to support vue3... There are some packages waiting for webpack-vue-config's vue3 support...

**Comment by raimund-schluessler** [comment]
Seems this PR is not necessary anymore. Closing.

**Pull request closed without merging**
